; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM

lib_deps =
    northernwidget/DS3231@^1.2.0 ; RTC
    zinggjm/GxEPD2 ; EINK
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    adafruit/Adafruit PN532 ;NFC/RFID Scanner
